name: focus_widget
description: When tap outside of the TextField, let the TextField lose focus.
version: 1.0.4+1
homepage: https://github.com/gzlock/flutter_focus_widget

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: