name: focus_widget
description: A focusable and blurable widget.
version: 1.0.0
author: gzlock88@gmail.com
homepage: https://github.com/gzlock/flutter_input

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: