name: focus_widget
description: When tap outside of the widget, let the FocusNode lose focus.
version: 1.0.5+2
homepage: https://github.com/gzlock/flutter_focus_widget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: